/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.awt.Image;
import java.awt.Toolkit;


/**
 *
 * @author GIOVANNI
 */
public class Welcome extends javax.swing.JFrame {
    public int opcion=0;
    /**
     * Creates new form VistaListaDoble
     */
    public Welcome() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setIconImage(this.getIconImage());
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/insignia.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btn_listaSimple = new javax.swing.JButton();
        btn_listaDoble = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 255, 255));
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 80, -1));

        btn_listaSimple.setBackground(new java.awt.Color(0, 51, 204));
        btn_listaSimple.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_listaSimple.setForeground(new java.awt.Color(255, 255, 255));
        btn_listaSimple.setText("LISTA SIMPLE");
        btn_listaSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listaSimpleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_listaSimple, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 200, 20));

        btn_listaDoble.setBackground(new java.awt.Color(102, 102, 255));
        btn_listaDoble.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_listaDoble.setForeground(new java.awt.Color(255, 255, 255));
        btn_listaDoble.setText("LISTA DOBLE");
        btn_listaDoble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listaDobleActionPerformed(evt);
            }
        });
        getContentPane().add(btn_listaDoble, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 200, -1));

        jLabel2.setBackground(new java.awt.Color(51, 51, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 30, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FRENTEWELCOM.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 1, 1, 1, new java.awt.Color(153, 255, 0)));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 300, 70));

        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoBienvenida.png"))); // NOI18N
        lbl_fondo.setText("ddd");
        getContentPane().add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_listaSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listaSimpleActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_listaSimpleActionPerformed

    private void btn_listaDobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listaDobleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_listaDobleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

  
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_listaDoble;
    public javax.swing.JButton btn_listaSimple;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel lbl_fondo;
    // End of variables declaration//GEN-END:variables
}
